# Generated by Django 4.2 on 2023-04-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0006_rename_name_expense_description_expensecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_date',
            new_name='date',
        ),
    ]
